# Generated by Django 3.1.7 on 2021-06-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Writen_Exam', '0002_auto_20210515_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinfo',
            name='time',
        ),
    ]
