# Generated by Django 3.1.7 on 2021-05-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('hard', 'hard'), ('easy', 'easy'), ('medium', 'medium')], max_length=6),
        ),
    ]
