# Generated by Django 3.1.7 on 2021-05-15 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Writen_Exam', '0002_auto_20210515_1709'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writing_question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='w_answer',
            name='created',
        ),
        migrations.AddField(
            model_name='w_answer',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Writen_Exam.examinfo'),
        ),
        migrations.AddField(
            model_name='w_answer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='w_answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='writing_question.w_question'),
        ),
    ]
