# Generated by Django 3.1.7 on 2021-06-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_question', '0002_auto_20210515_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='w_question',
            name='time',
            field=models.FloatField(default=1, help_text='duration of the quiz in minutes'),
        ),
    ]
